/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SimdVectorComputeService */

#ifndef _Included_org_opensearch_knn_jni_SimdVectorComputeService
#define _Included_org_opensearch_knn_jni_SimdVectorComputeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkDistanceCalculation
 * Signature: ([I[FI)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_scoreSimilarityInBulk
  (JNIEnv *, jclass, jintArray, jfloatArray, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    saveSearchContext
 * Signature: ([F[JI)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_saveSearchContext
  (JNIEnv *, jclass, jfloatArray, jlongArray, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    scoreSingleVector
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_scoreSimilarity
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    saveSQSearchContext
 * Signature: ([BFFFI[JIIF)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_saveSQSearchContext
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat, jint, jlongArray, jint, jint, jfloat);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkQuantizedDotProduct
 * Signature: ([B[B[FIII)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_bulkQuantizedDotProduct
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jfloatArray, jint, jint, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkCentroidDistance
 * Signature: ([F[F[FIII)I
 */
JNIEXPORT jint JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_bulkCentroidDistance
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkSOARDistance
 * Signature: ([F[F[F[FIIF)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_bulkSOARDistance
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
